### PR TITLE
The Missing Color-Wheel Directive

### PR DESCRIPTION
**Pull request by MHabashy10**
Hi Everyone,

Thank you so much for this awesome widgets, while we was working with your color-wheel directive, we believe you missed this directive in the distribution files, so i wrote it back from the version used in the demo.

**Thanks** to James for reporting and pinpoint this issue. #3

Thanks again for this awesome widgets specially color-wheel. :+1: 

Kind Regards,
Mohamed

### CODE REVIEW

**Comment by MHabashy10** [comment]
anyone interested? 
@spike886

**Comment by spike886** [comment]
Thanks a lot

**Comment by spike886** [comment]
After analyze the problem, i released the that directive was deplicated and renamed as light-color-editor.
The problem was that  the demo had a old version.
I will fix that and update the documentation and the demo to prevent this problem

**Comment by MHabashy10** [comment]
Excellent, You are welcome 🙂 happy to help.
looking forward for your awesome updates, have to tell you that your color wheel is the best i had ever seen, thank you so much.
Best Wishes.

**Comment by spike886** [comment]
Please check the last version v0.3.2
It should fix the problems

**Comment by MHabashy10** [comment]
Awesome, 🙂  thank you so much 👍

**Pull request merged**
